name: release

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Setup git
        run: |
          git config user.name "GitHub Bot"
      - name: Install dependencies
        run: npm ci
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: setSHAs
        uses: nrwl/nx-set-shas@v4
        with:
          last-successful-event: 'pull-request'
          main-branch-name: 'main'
      - name: Run versioning
        shell: bash
        run: |
          npx nx affected \
          --base=${{ env.NX_BASE }} \
          --head=${{ env.NX_HEAD }} \
          --target=version \
          --parallel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push release commit with created tag to remote
        shell: bash
        run: |
          git push --follow-tags origin main --force
